### ISSUE TITLE
version number incomplete on macOS

### ISSUE THREAD

**Issue by core-code** [dashpay/dash#2423]
i've downloaed version 0.12.3.3 on macOS, but when selecting it on the Finder it only says 'Version 0.12.3'

since there are quite critical differences even between the minor versions could you make sure the complete version number is embedded into the app, at least into the CFBundleVersion entry? so that one can check which version one has.

**Comment by nmarley** [comment]
There's a recently opened PR in the Bitcoin upstream which adds just this: https://github.com/bitcoin/bitcoin/pull/14701

Once that's merged upstream, we can backport it into Dash.

**Comment by core-code** [comment]
thanks

**Comment by PastaPastaPasta** [comment]
fixed by #2687 @UdjinM6

**Comment by core-code** [comment]
note that this still appears in the new version '0.14.0.3'

its embedded version number is 0.14.0

i thought this was supposed to be fixed?

**Comment by UdjinM6** [comment]
Hmm... Indeed. At least on recent macOS (10.14.6).
<img width="522" alt="Screenshot 2019-08-29 at 01 31 59" src="https://user-images.githubusercontent.com/1935069/63897147-da204400-c9fc-11e9-958f-189dacf8dacd.png">
Though it looks like Bitcoin Core build has the same issue too now.
<img width="418" alt="Screenshot 2019-08-29 at 01 32 07" src="https://user-images.githubusercontent.com/1935069/63897213-1358b400-c9fd-11e9-8d43-6fa73a0109d6.png">

**Comment by UdjinM6** [comment]
Ah... I see what's going on. that patch fixed the way it's displayed in Inspector but Preview does this differently.

**Comment by core-code** [comment]
from your Info.plist file:

```

  <key>CFBundleGetInfoString</key>
  <string>0.14.0.3, Copyright © 2009-2019 The Bitcoin Core developers, 2014-2019 The Dash Core developers</string>

  <key>CFBundleShortVersionString</key>
  <string>0.14.0</string>

  <key>CFBundleVersion</key>
  <string>0.14.0</string>
```

the real version numbers (CFBundleVersion and CFBundleShortVersionString) are at "0.14.0" which is incorrect.

only the old "CFBundleGetInfoString" key which has been deprecated for more than 10 years and should just be removed contains the full version number.

**Comment by UdjinM6** [comment]
We still build for older macOS versions (10.8+), so we probably can't drop `CFBundleGetInfoString` that easy. Anyway, pls see #3074, I hope it should finally fix the issue (at least it did on my local machine).

**Comment by core-code** [comment]
`CFBundleGetInfoString` has been deprecated in 10.6, it is not necessary for 10.8+

thanks, looking forward to #3074 landing ;)
